backend:
  name: git-gateway
  branch: main # <-- IMPORTANT: Confirm this matches your GitHub repo's default branch (e.g., 'main' or 'master')

media_folder: brighterBeginnings/public/uploads # All general media (like images for blog posts, etc.) will go here
public_folder: /uploads

collections:
  - name: "programs" # The internal name for this collection
    label: "Programs" # What editors see in the CMS sidebar
    folder: "brighterBeginnings/content/programs" # Where the content files will be stored in your Git repo
    create: true # Allows editors to create new program entries
    slug: "{{slug}}" # Automatically generates filename from the title
    extension: "json" # Save content as .json files for easier parsing in React
    format: "json" # Use JSON format for the content

    fields:
      # Top-level fields for each program object (img and bg_color removed)
      - {label: "Accordion Title", name: "accordion_title", widget: "string", required: true, hint: "e.g., Infant Program Details"}
      - {label: "Program Image Path", name: "img", widget: "string", disabled: true, required: true, hint: "Path to the program's image (e.g., /img/infant.png). Not editable in CMS."}
      - {label: "Age Range Text", name: "age", widget: "string", hint: "e.g., 6 Weeks - 15 Mo"}
      - {label: "Age Start (Months)", name: "start", widget: "number", value_type: "float", min: 0, hint: "Starting age in months (e.g., 1.5 for 1 month, 2 weeks)"}
      - {label: "Age End (Months)", name: "end", widget: "number", value_type: "float", min: 0, hint: "Ending age in months (e.g., 15 for 1 year, 3 months)"}

      # Nested array of objects: dropdownData
      - label: "Program Details (Dropdowns)" # Label for this list in the CMS UI
        name: "dropdownData" # The key name for this array in your content file
        widget: "list" # This tells Netlify CMS it's an array of items
        collapsed: false # Keep the list open by default in the CMS
        summary: "{{fields.title}}" # Show the title of each dropdown item in the list summary
        fields: # These are the fields for EACH item within the dropdownData list (color removed)
          - {label: "Dropdown Title", name: "title", widget: "string", required: true, hint: "e.g., Price, Description, Schedule"}
          - {label: "Dropdown Description", name: "description", widget: "markdown", required: true, hint: "Detailed text for this dropdown item"}

  - name: "pages" # Your existing 'Website Pages' collection
    label: "Website Pages"
    files:
      - file: "brighterBeginnings/content/pages/home.json" # This will be the content file for your Home page
        label: "Home Page" # Label in the CMS UI
        name: "home_page_content" # Internal name for this file entry
        fields:
          - {label: "Page Title (SEO)", name: "title", widget: "string", required: true, hint: "The main title for SEO and internal reference, e.g., Brighter Beginnings Home"}

          # --- Carousel Section ---
          - label: "Carousel Slides"
            name: "carousel_slides"
            widget: "list"
            collapsed: false
            summary: "{{fields.background_image}} - {{fields.heading}}" # Use image path and heading for summary
            fields:
              - {label: "Background Image", name: "background_image", widget: "image", required: false, hint: "Image for the main carousel slide background."}
              - {label: "Overlay Image (Optional)", name: "overlay_image", widget: "image", required: false, hint: "Smaller image to overlay on the background (e.g., Heggerty logo)."}
              - {label: "Image Container Background Color", name: "container_bg_color", widget: "color", required: false, default: "#ffffff", hint: "Background color for slide if overlay image is used (e.g., #89c9d0)."} # For the Heggerty slide, use #89c9d0 for light-sky
              - {label: "Heading", name: "heading", widget: "string", required: false, hint: "Main text for the slide, e.g., Get to know our Staff!"}
              - {label: "Subheading", name: "subheading", widget: "string", required: false, hint: "Secondary text for the slide, e.g., 5 large fenced in play areas..."}
              - {label: "Button Text", name: "button_text", widget: "string", required: false, hint: "Text on the call-to-action button, e.g., Learn More!"}
              - {label: "Button Link", name: "button_link", widget: "string", required: false, hint: "Internal path (e.g., /staff) or external URL."}
              - {label: "Video Embed URL (Optional)", name: "video_url", widget: "string", required: false, hint: "YouTube or similar embed URL (e.g., https://www.youtube.com/embed/VIDEO_ID). Only for video slides."}
              - {label: "Video Button Text (Optional)", name: "video_button_text", widget: "string", required: false, hint: "Text for the 'Click to Play Video' button."}
           # --- Carousel Section ---
          - label: "Class Dojo Description"
            name: "class_dojo_description"
            widget: "list"
            collapsed: false
            summary: "{{fields.bullet_point}}" # Use image path and heading for summary
            fields:
              - {label: "Class dojo description", name: "bullet_point", widget: "string", required: true, hint: "bullet point describing class dojo"}          # --- Placeholders for other Home page components (CareersContent, ClassDojo)
          # You'll expand these as you move more content into the CMS.
          # For now, we'll keep them as simple placeholders.
          - {label: "We provide programs title", name: "we_provide_programs_title", widget: "string", required: false}
          - {label: "ClassDojo Title", name: "classdojo_title", widget: "string", required: false}
          - {label: "Careers Section Heading", name: "careers_heading", widget: "string", required: true}
          - {label: "Careers Section Text", name: "careers_text", widget: "string", required: true}
          - {label: "Careers Section Link", name: "careers_link", widget: "string", required: true}


      - file: "brighterBeginnings/content/pages/about.json" # Or about.md, if you prefer Markdown for pages
        label: "About Page"
        name: "about"
        fields:
          - label: "Page Main Image"
            name: "main_image"
            widget: "image"
            required: true
          
          - label: "Play & Learn Areas"
            name: "play_learn_data"
            widget: "list"
            required: true
            min: 3
            max: 4

            fields:
              - label: "Carousel Image"
                name: "carouselImg"
                widget: "image"
                required: true
              - label: "Carousel Title"
                name: "carouselTitle"
                widget: "string"
                required: true
              - label: "Carousel Description Points"
                name: "carouselDescription"
                widget: "list"
                min: 2
                max: 3
                collapsed: false
                required: true
                
                fields:
                  - label: "Description Point"
                    name: "point"
                    widget: "string"
                    required: true
          - label: "Philosophy Data"
            name: "philosophyData"
            widget: "object"
            required: true
            collapsed: false
            # Only 'dropdownData' is editable within philosophyData
            fields:
              - label: "Dropdown Data"
                name: "dropdownData"
                widget: "list"
                required: true
                collapsed: false
                fields:
                  - label: "Title"
                    name: "title"
                    widget: "string"
                    required: true
                  - label: "Description"
                    name: "description"
                    widget: "text" # Using 'text' widget for potentially longer descriptions
                    required: true

      # --- NEW: Reviews Page Content ---
      - file: "brighterBeginnings/content/pages/reviews.json" # Path to the content file for your Reviews page
        label: "Reviews Page" # Label in the CMS UI for this specific file
        name: "Reviews Page"
        fields:
          # --- This field allows the user to edit the main page title in CMS ---
          - {label: "Page Title", name: "title", widget: "string", required: true, hint: "The main title displayed on the Reviews page, e.g., Customer Reviews"}
          # --- The 'image' widget for 'banner_image' specifically allows photo uploads/selection via CMS ---
          - {label: "Banner Image", name: "banner_image", widget: "image", required: false, hint: "Upload the main banner image for the Reviews page."}
          # --- These fields allow editing the banner text ---
          - {label: "Banner Title", name: "banner_title", widget: "string", required: true, hint: "e.g., Lily Smith"}
          - {label: "Banner Subtitle", name: "banner_subtitle", widget: "string", required: true, hint: "e.g., Brighter Beginnings Director"}

          # --- These fields allow editing the introductory paragraphs ---
          - {label: "Intro Paragraph 1", name: "paragraph_1", widget: "markdown", required: true}
          - {label: "Intro Paragraph 2 (Desktop)", name: "paragraph_2_desktop", widget: "markdown", required: false}
          - {label: "Intro Paragraph 3 (Desktop)", name: "paragraph_3_desktop", widget: "markdown", required: false}
          - {label: "Sign-off Text", name: "sign_off_text", widget: "string", required: true}

          # --- This section allows adding/editing/removing review platforms and their links ---
          - label: "Review Platforms" # Label for the list in CMS
            name: "review_platforms" # Key in the JSON
            widget: "list"
            collapsed: false
            summary: "{{fields.platform_name}}" # Show the platform name in the list summary
            fields:
              # Fields for each individual review platform entry:
              - {label: "Platform Name", name: "platform_name", widget: "string", required: true, hint: "e.g., Facebook, Google"}
              - {label: "Icon Key", name: "icon_key", widget: "string", required: true, hint: "e.g., facebook, google, yelp, care (must match hardcoded names for logos)"}
              - {label: "Desktop Review Link", name: "desktop_link", widget: "string", required: true, pattern: ["^https?:\/\/.+", "Must be a valid URL starting with http:// or https://"], hint: "Full URL for desktop reviews"}
              - {label: "Mobile Review Link", name: "mobile_link", widget: "string", required: true, pattern: ["^https?:\/\/.+", "Must be a valid URL starting with http:// or https://"], hint: "Full URL for mobile reviews"}
              - {label: "Icon Alt Text", name: "icon_alt_text", widget: "string", required: true, hint: "e.g., Facebook icon"}
      - file: "brighterBeginnings/content/pages/photo_gallery.json" # Define the path for your new photo gallery content file
        label: "Photo Gallery Page" # Label in the CMS UI sidebar
        name: "photo_gallery_page_content" # Internal name for this file entry
        fields:
          # Page Title
          - {label: "Gallery Page Title", name: "title", widget: "string", required: true, hint: "The main title displayed on the photo gallery page, e.g., Photo Gallery"}

          # Descriptions
          - label: "Long Description (Desktop)"
            name: "long_description"
            widget: "string" # Use markdown for rich text editing
            required: true
            hint: "Detailed introductory text for the photo gallery, typically displayed on larger screens."
          - label: "Short Description (Mobile)"
            name: "short_description"
            widget: "string" # Use markdown for rich text editing
            required: true
            hint: "Concise introductory text for the photo gallery, typically displayed on mobile screens."

          # Gallery Photos (List Widget)
          - label: "Gallery Photos" # Label for the list in CMS UI
            name: "gallery_photos" # This will be the array key in your JSON
            widget: "list"
            collapsed: false # Keep the list items expanded by default
            summary: "{{fields.src}}" # Show the image source path in the list summary
            fields: # Fields for EACH individual photo item in the list
              - {label: "Image File", name: "src", widget: "image", required: true, hint: "Upload the photo for the gallery."}
      - file: "brighterBeginnings/content/pages/forms.json" # Define the path for your new photo gallery content file
        label: "Forms Page" # Label in the CMS UI sidebar
        name: "forms_page_content" # Internal name for this file entry
        fields:
          # Page Title
          - {label: "Accordion Title", name: "accordion_title", widget: "string", required: true, default: "Available Forms"}
          - label: "Dropdown Sections"
            name: "dropdownData"
            widget: "list"
            collapsed: false
            summary: "{{fields.title}}" # How each dropdown item is labeled in the CMS list
            fields:
              - {label: "Dropdown Title", name: "title", widget: "string", required: true}
              
              # This is the nested list for the individual links within each dropdown
              - label: "Links List"
                name: "links"
                widget: "list"
                collapsed: true # Keep this collapsed by default for cleaner UI
                summary: "{{fields.text}}" # How each link is labeled in the CMS list
                fields:
                  - {label: "Link Text", name: "text", widget: "string", required: true, hint: "The visible text for the link"}
                  - {label: "Link URL", name: "url", widget: "string", required: true, pattern: ["^https?:\/\/.+", "Must be a valid URL starting with http:// or https://"], hint: "The full URL to the PDF or web page"}
              

      