const fs = require('fs');
const path = require('path');

const programsPath = path.join(__dirname, '..', 'content', 'programs'); // Path to your CMS content
const outputFilePath = path.join(__dirname, '..', 'src', 'data', 'programs.js'); // Where the generated data will go

// Ensure the output directory exists
const outputDir = path.dirname(outputFilePath);
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

let programs = [];

// Read all program JSON files
if (fs.existsSync(programsPath)) {
  const programFiles = fs.readdirSync(programsPath).filter(file => file.endsWith('.json'));

  for (const file of programFiles) {
    const filePath = path.join(programsPath, file);
    const fileContent = fs.readFileSync(filePath, 'utf8');
    try {
      const programData = JSON.parse(fileContent);
      programs.push(programData);
    } catch (error) {
      console.error(`Error parsing JSON from ${file}:`, error);
    }
  }
} else {
  console.warn(`Warning: '${programsPath}' directory not found. No programs will be loaded.`);
}


// Sort programs by 'start' (age in months), just like your original array
programs.sort((a, b) => a.start - b.start);


// Generate the JavaScript file that exports the programs array
const jsContent = `
// This file is auto-generated by generate-data.js. Do not edit manually.
const availablePrograms = ${JSON.stringify(programs, null, 2)};

export default availablePrograms;
`;

fs.writeFileSync(outputFilePath, jsContent, 'utf8');

console.log(`Generated ${programs.length} program entries to ${outputFilePath}`);